language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk12
services:
  - postgresql
before_script:
  - psql -c 'create database mimic;' -U postgres
script: mvn test -Pci -B
after_success:
  - mvn clean test -Pci jacoco:report coveralls:report
cache:
  directories:
  - $HOME/.m2
